### Creates a new patient
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Kamella Hoang",
  "email": "kamella.nhoang@senecapolytechnic.ca",
  "address": "191 McNicoll Ave",
  "dateOfBirth": "2005-08-01",
  "registeredDate": "2023-05-22"
}

###