### Creates a new patient
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "John Cena",
  "email": "john.cena@senecapolytechnic.ca",
  "address": "1200 Sheppard E Ave",
  "dateOfBirth": "1982-08-01",
  "registeredDate": "2025-05-20"
}

###