### Creates a new patient
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Vladyslav Huziienko",
  "email": "vladyslav.huziienko@senecapolytechnic.ca",
  "address": "1890 Sheppard E Ave",
  "dateOfBirth": "2005-08-01",
  "registeredDate": "2025-05-20"
}

###